name: Reusable Vercel Deploy Workflow

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch name to deploy'
        required: false
        default: 'vercel'
        type: string
      git_name:
        description: 'Git user.name to set'
        required: false
        default: 'GitHub Actions'
        type: string
      git_email:
        description: 'Git user.email to set'
        required: false
        default: 'actions@github.com'
        type: string
      commit_message:
        description: 'Commit message to use'
        required: false
        default: "Add files for Vercel deployment at $(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M:%S')"
        type: string

jobs:
  create-vercel-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Keep only Vercel deploy files
        run: |
          chmod +x scripts/clean-unwanted-files.sh
          bash scripts/clean-unwanted-files.sh

      - name: Configure Git
        run: |
          git config user.name "${{ inputs.git_name }}"
          git config user.email "${{ inputs.git_email }}"

      - name: Commit and push to vercel branch
        run: |
          git fetch origin ${{ inputs.branch }} || echo "No existing branch."
          git checkout -b ${{ inputs.branch }} || git checkout ${{ inputs.branch }}
          xargs -a .vercelkeep -I {} git add {}
          git commit -m "${{ inputs.commit_message }}"
          git push origin ${{ inputs.branch }} --force
