name: Test Vercel Deploy Workflow

on:
  push:
    branches:
      - master
  pull_request:

env:
  root_path: test-vercelkeep

jobs:
  test-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test clean-unwanted-files.sh
        run: |
          chmod +x scripts/docker-run.sh
          bash scripts/docker-run.sh

      - name: Setup files
        run: |
          chmod +x test/workflow/setup.sh
          bash test/workflow/setup.sh

      - name: Test workflow
        uses: ./.github/actions
        with:
          branch: "test-vercel"
          git_name: "Test Actions"
          git_email: "test@example.com"
          commit_message: "Test Commit for Vercel Deployment"
